[package]
name = "hedge"
version = "0.1.0"
authors = ["Chip Collier <photex@gmail.com>"]

description = "An index based half-edge mesh implementation."

repository = "https://gitlab.com/photex/hedge"

keywords = ["halfedge", "half-edge", "mesh", "half edge", "graphics", "meshes"]
categories = ["graphics"]

license = "MPL-2.0"

[dependencies]
