[package]
name = "hedge"
version = "0.0.12"
authors = ["Chip Collier <photex@gmail.com>"]

description = "An index based half-edge mesh implementation."


keywords = ["halfedge", "half-edge", "mesh", "graphics", "meshes"]
categories = ["data-structures"]

license = "MPL-2.0"

documentation = "https://docs.rs/hedge"
homepage = "https://github.com/photex/hedge"
repository = "https://github.com/photex/hedge"
readme = "README.md"

[dependencies]
log = "0.3"

[dependencies.cgmath]
optional = true
version = "0.15"

[dependencies.nalgebra]
optional = true
version = "0.13"

[dev-dependencies]
env_logger = "0.4"

[features]
default = ["cgmath"]
with_nalgebra = ["nalgebra"]
